# Generated by Django 3.2.7 on 2021-09-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitexerciseelement',
            name='type',
            field=models.CharField(choices=[('SELECT_VIEW', 'ОТВЕТ С ВЫБОРОМ'), ('TRUE_OR_FALSE_VIEW', 'ПРАВДА ИЛИ ЛОЖЬ'), ('FREE_ANSWER_VIEW', 'СВОБОДНЫЙ ТИП ОТВЕТОВ')], max_length=60, verbose_name='Тип элемента'),
        ),
        migrations.AlterField(
            model_name='unittheoryelement',
            name='type',
            field=models.CharField(choices=[('LIST_VIEW', 'Список'), ('PLAIN_TEXT_VIEW', 'Текст'), ('IMAGE_VIEW', 'Изображение'), ('IMAGE_BETWEEN_TEXT', 'Изображение, между текстами'), ('IMAGE_LEFT_TEXT_VIEW', 'Изображение, текст слева'), ('IMAGE_RIGHT_TEXT_VIEW', 'Изображение, текст справа')], max_length=60, verbose_name='Тип элемента'),
        ),
        migrations.CreateModel(
            name='UnitExerciseElementAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время создания объекта')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время последнего обновления объекта')),
                ('data', models.CharField(max_length=255, verbose_name='Варинаты ответов или правильные ответы(зависиот от типа упражнения)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Индикатор который указывает на правильность варинта(не для FREE_ANSWER_VIEW)')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='unit.unitexerciseelement', verbose_name='Упражнение юнита')),
            ],
            options={
                'verbose_name': 'Варианты ответов для упражнения юнита',
                'verbose_name_plural': 'Варианты ответов для упражнения юнитов',
            },
        ),
    ]
