# Generated by Django 3.2.7 on 2021-09-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unit", "0002_auto_20210928_0925"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitexerciseelement",
            name="content",
            field=models.CharField(max_length=500, verbose_name="Контент элемента"),
        ),
    ]
