# Generated by Django 3.2.7 on 2021-10-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unit", "0009_alter_unittheoryelement_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="unittheoryelement",
            name="order_number",
            field=models.IntegerField(default=0),
        ),
    ]
