# Generated by Django 3.2.7 on 2021-10-15 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unit", "0011_auto_20211014_1842"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unitexerciseelementanswer",
            options={
                "verbose_name": "Вариант ответа упражнения юнита",
                "verbose_name_plural": "Варианты ответов для упражнения юнитов",
            },
        ),
        migrations.CreateModel(
            name="UnitUserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время создания объекта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Время последнего обновления объекта",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unit.unitexerciseelementanswer",
                        verbose_name="Ответ пользователя",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answer",
                        to="unit.unitexerciseelement",
                        verbose_name="Упражнение",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="unit.unit",
                        verbose_name="Юнит",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ юзера на вопрос",
                "verbose_name_plural": "Ответы юзеров на вопросы",
            },
        ),
    ]
