# Generated by Django 3.2.7 on 2021-10-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0014_unit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='access_plan',
            field=models.CharField(choices=[('FREE_PLAN', 'Бесплатная подписка'), ('PREMIUM_PLAN', 'Премиальная подписка')], default=1, max_length=30, verbose_name='Уровень подписки для просмотра юнита'),
            preserve_default=False,
        ),
    ]
