# Generated by Django 3.2.7 on 2021-10-25 14:49

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0015_unit_access_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='unituseranswer',
            name='json_answer',
            field=models.JSONField(blank=True, default={'answers': {0: 1}, 'variants': ['data']}, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Поле ответов для IN_TEXT типов вопросов'),
        ),
        migrations.AlterField(
            model_name='unituseranswer',
            name='answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unit.unitexerciseelementanswer', verbose_name='Ответ пользователя'),
        ),
    ]
