# Generated by Django 3.2.7 on 2021-10-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время создания объекта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Время последнего обновления объекта",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название предмета"),
                ),
                ("cost", models.IntegerField(default=0)),
                (
                    "source",
                    models.ImageField(blank=True, null=True, upload_to="unitassets"),
                ),
            ],
            options={
                "verbose_name": "Продукт магазина",
                "verbose_name_plural": "Продукты магазина",
            },
        ),
    ]
