# Generated by Django 3.2.7 on 2021-09-22 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUnitRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время создания объекта')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время последнего обновления объекта')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс прохождения юнита')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_users', to='unit.unit', verbose_name='Юнит')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_units', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отношение юнита и пользователя',
                'verbose_name_plural': 'Отношений юнитов и пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserPurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время создания объекта')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время последнего обновления объекта')),
                ('points', models.IntegerField(default=0, verbose_name='Счет пользователя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purse', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кошелек пользователя',
                'verbose_name_plural': 'Кошелький пользователей',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время создания объекта')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время последнего обновления объекта')),
                ('type', models.CharField(choices=[('UNIT_FINISHED', 'Unit Finished'), ('POINTS_EARNED', 'Points Earned'), ('PURCHASE', 'Purchase'), ('NOTIFICATION', 'Notification')], max_length=30, verbose_name='Тип ивента')),
                ('message', models.CharField(max_length=255, verbose_name='Текст ивента')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ивент пользователя',
                'verbose_name_plural': 'Ивенты пользователей',
            },
        ),
    ]
