# Generated by Django 3.2.7 on 2021-10-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0002_userpurchases"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpurchases",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="authentication.fiureaduser",
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
    ]
