# Generated by Django 3.2.7 on 2021-10-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_userpurchases_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpurchases",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
